name: 'Install Dependencies'
description: 'Install dependencies using Poetry'

inputs:
  dependency-groups:
    description: 'Poetry dependency groups to install'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
      shell: bash

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: '1.4.2'
      shell: bash

    - name: Install dependencies
      run: poetry install --only ${{ inputs.dependency-groups }}
      shell: bash
