name: Bundle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          dependency-groups: "root,build"
      - name: Bundle
        run: scripts/bundle.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: ./dist/deletion_helper
