name: Bundle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.2
      - name: Install dependencies
        run: poetry install --only root,build
      - name: Bundle
        run: scripts/bundle.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: ./dist/deletion_helper
