name: Continuous Integration

on:
  push:
    branches:
      - "*" # Pushes to any branch
  pull_request:
    branches:
      - "*" # Pull requests to any branch
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/workflows/install-dependencies.yml
        with:
          dependency-groups: "root,dev,test,build"
      - name: Run pytest
        run: poetry run pytest --junitxml=test-results.xml --cov=deletion_helper --cov-report=html
        continue-on-error: true
      - name: Run ruff
        run: poetry run ruff
        continue-on-error: true
      - name: Run black
        run: poetry run black --check --diff .
        continue-on-error: true
      - name: Install mypy
        run: poetry add mypy -E dev
        continue-on-error: true
      - name: Run mypy
        run: poetry run mypy deletion_helper
        continue-on-error: true
      - name: Archive pytest results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: |
            ./test-results.xml
            ./htmlcov
