name: Continuous Integration

on:
  push:
    branches:
      - "*" # Pushes to any branch
  pull_request:
    branches:
      - "*" # Pull requests to any branch
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          dependency-groups: "root,dev,test,build"
      - name: Run pytest
        run: poetry run pytest --junitxml=test-results.xml --cov=deletion_helper --cov-report=html
      - name: Run ruff
        if: success() || failure()
        run: poetry run ruff check .
      - name: Run black
        if: success() || failure()
        run: poetry run black --check --diff .
      - name: Run mypy
        if: success() || failure()
        run: poetry run mypy deletion_helper
      - name: Archive pytest results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: |
            ./test-results.xml
            ./htmlcov
